lexik_maintenance:
    authorized:
        path: /api
        ips: ['127.0.0.1', 10.10.2.0]
    driver:
        ttl: 3600
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'
        options:
            file_path: '%kernel.root_dir%/cache/lock'
