security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_API]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_API]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    acl:
        connection: default

    providers:
        fos_userbundle:
            id: fos_user.user_manager
#        in_memory:
#            memory: ~

    firewalls:
        dev:
            pattern:            ^/(_(profiler|wdt|error)|css|images|js)/
            security:           false

        admin:
            pattern:            ^/admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true

        main:
            pattern:            ^/(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true

        rest_api:
            pattern:            ^/api/(.*)
            stateless:          true
            http_basic:
                provider:       fos_userbundle

        default:
            anonymous: ~

    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api/user, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api/*, role: ROLE_API }
        - { path: ^/admin/*, role: [ ROLE_ADMIN, ROLE_SONATA_ADMIN, ] }
        - { path: ^/profile/*, role: ROLE_USER }
        - { path: ^/delivery/*, role: ROLE_USER }
        - { path: ^/target/[^/]$, role: ROLE_USER }
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ] }

